#!/usr/bin/env php
<?php

if ($argc < 3 || $argv[1] !== 'new') {
    echo "Usage : kyra-framework new nom-du-projet\n";
    exit(1);
}

$projectName = $argv[2];
$zipUrl = 'https://github.com/kyra-andriatsitohaina/kyra-framework/archive/refs/heads/main.zip';

echo "Téléchargement du framework Kyra...\n";
copy($zipUrl, 'framework.zip');

$zip = new ZipArchive;
if ($zip->open('framework.zip') === TRUE) {
    $zip->extractTo('.');
    $zip->close();
    unlink('framework.zip');

    rename('kyra-framework-main', $projectName);
    echo "Projet '$projectName' créé avec succès.\n";
} else {
    echo "Erreur lors du téléchargement.\n";
}
